### ISSUE TITLE
Installation Workflow with custom Extensions

### ISSUE THREAD

**Issue by Mariyo** [bolt/composer-install#13]
Can you please help me with this scenario?

1. I install Bolt  with command ```composer create-project bolt/composer-install:^3.0```
2. I add custom extension with command ```composer require "bolt/bolt-extension-starter-extended"```
3. When its done, there are no ```web``` assets from extension in ```public``` folder of bolt, neither in ```public/bolt-public```

Should I run ```nut``` command? If so, which command? I've tried some, but without success.

Thx

**Comment by CarsonF** [comment]
2. Should be: `vendor/bin/nut extension:install bolt/bolt-extension-starter-extended`

**Comment by Mariyo** [comment]
@CarsonF thx for quick answer... It seems fine except this error message:
```
[InvalidArgumentException]
  Could not find package bolt/bolt-extension-starter-extended at any version
  for your minimum-stability (stable). Check the package spelling or your min
  imum-stability
```

when I run ```./vendor/bin/nut extensions:install bolt/bolt-extension-starter-extended v3```

**Comment by CarsonF** [comment]
`^3.0` not `v3

**Comment by Mariyo** [comment]
Same story... 

PS: I've tried ```*``` also, but different error...

**Comment by GawainLynch** [comment]
OK… there may be some miscommunication happening here :smile: 

The starter extension is not available from the marketplace (only packagist.og) so you can't use nut … Composer installs will not trigger asset installs, for that you need to install packages from the market place.

The starter extension is an example extension to help people to build extensions.

**Comment by Mariyo** [comment]
@GawainLynch Ok, its more clear now. Just wondering, is it possible to add another source except marketplace? Lets say private Bitbucket or GitHub repo?

**Comment by SahAssar** [comment]
@Mariyo You can either setup satis and add your source there or you should be able to add from a VCS like this: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by Mariyo** [comment]
@SahAssar This way I know, that I can add VCS to composer.json, but I wanted to test if this scenario is possible:

1. I will install Bolt ```composer create-project bolt/composer-install:^3.0```
2. I will add source of my extension ```./vendor/bin/nut extensions:vcs https://github.com/igorw/monolog```
3. I will install my extension from my VCS ```./vendor/bin/nut extensions:install igorw/monolog```

But it seems, that I will have to create my own project based on ```bolt/composer-install``` and add there VCS and custom requirements (dependencies) to ```composer.json``` like ```bolt/bolt-extension-starter-extended``` has.

**Comment by GawainLynch** [comment]
@Mariyo I think you are mixing up a few concepts here … I know I did when I first started using Composer to build project … plus the added complexity of how Bolt is structured internally.

You mention a package like `igorw/monolog` … this is the sort of thing that you would add to the root project, so for example:

```
composer create-project bolt/composer-install:^3.0 my-new-project
cd my-new-project/
composer require igorw/monolog:^1.0
```

If, however, you just wanted to install Bolt, and then add the `bolt/boltforms` **Bolt extension**, the process would look like:

```
composer create-project bolt/composer-install:^3.0 my-new-project
cd my-new-project/extensions/
composer require bolt/boltforms:^3.0
```

Or same thing, using the Nut command:

```
composer create-project bolt/composer-install:^3.0 my-new-project
cd my-new-project/extensions/
./app/nut extensions:install bolt/boltforms:^3.0
```

Alternatively if you want to install a **Bolt extension** from a GitHub, or GitLab repository:
```
composer create-project bolt/composer-install:^3.0 my-new-project
cd my-new-project/extensions/
```

Edit the `extensions/composer.json` file to be similar to this:
```
    "repositories": {
        "my-extension": {
            "type": "vcs",
            "url": "https://github.com/YourOrg/YourRepo.git"
        },
        "bolt": {
            "type": "composer",
            "url": "https://extensions.bolt.cm/satis/"
        },
        "packagist": false
    },
```

Then you can use either Composer or Nut to install the package:
```
composer require authorname/extensionname:^1.0
```

**Comment by Mariyo** [comment]
@GawainLynch Yes, you are right, I am mixing few concepts :) Anyways, your answer helped me to understand extensions setup in Bolt.

Thank you

**Comment by GawainLynch** [comment]
You're very welcome mate… I had the same problem when figuring it all out too :smile:
