### ISSUE TITLE
Add {$public directory}/bolt-public to .gitignore

### ISSUE THREAD

**Issue by sbani** [bolt/composer-install#4]
I would add the created public dir to the .gitignore file automatically, because there is no need to track the vendor specific files.

**Comment by CarsonF** [comment]
This already exists: [public/bolt-public/.gitignore](https://github.com/bolt/composer-install/blob/master/public/bolt-public/.gitignore)

**Comment by GawainLynch** [comment]
Given that this was opened before we implemented this, I am going to call job done.

As always, @sbani, you're most welcome to reopen if things are not to your satisfaction.
