### ISSUE TITLE
No .htaccess after install

### ISSUE THREAD

**Issue by gander** [bolt/composer-install#5]
No .htaccess exists in "public" dir after install

**Comment by nlemoine** [comment]
I also raised this issue here: https://github.com/bolt/bolt/issues/3551

Composer install really need improvments.

**Comment by Bogardo** [comment]
:+1:

**Comment by ToBe998** [comment]
Imho, keeping the webserver specific stuff optional and out of the installer is perfectly fine. At the moment we have the problem however, that you arent even told that you might need to add "something" to whatever config you are using to make it work.

So i see two options:

1) Just add a proper info to the documentation pages about installation. Maybe even add sample for the top used webservers (apache and nginx?)

2) Let the installer ask the user and either create the necessary files for apache or nginx or just hint on it.

**Comment by GawainLynch** [comment]
Agree on all points… would welcome PRs from anyone with the bandwidth.
